[package]
name = "chessboard_cell_color"
version = "0.1.0"
authors = ["Ben Mertz <ben.mertz.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
